# Generated by Django 3.1.7 on 2021-03-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210305_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidado',
            name='dt_eleiçao',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
