# Generated by Django 3.1.7 on 2021-03-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidado_dt_eleiçao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidado',
            name='dt_nascimento',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
