# Generated by Django 3.1.7 on 2021-03-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210305_1602'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidado',
            new_name='Candidato',
        ),
    ]
